

- name: USER | Create SSH key on ldap server
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: "{{ peertube_ssh_key_bits | default (omit) }}"
    ssh_key_comment: "root@{{ inventory_hostname }}"
  delegate_to: '{{ peertube_ldap_url }}'

- name: COMMAND | Extract SSH ldap server pub key
  command: "cat /root/.ssh/id_rsa.pub"
  register: cat
  changed_when: false
  delegate_to: "{{ peertube_ldap_url }}"

- name: Add SSH server pub key to peertube
  authorized_key:
    user: root
    state: present
    key: "{{ cat.stdout }}"

- name: SHELL | ssh public key of peertube
  shell: "ssh-keyscan {{ inventory_hostname }}"
  register: ssh_known_host_results
  ignore_errors: yes
  delegate_to: "{{ peertube_ldap_url }}"
  become_user: root

- name: KNOWN_HOSTS | add or update client key to known_hosts in server
  known_hosts:
    path: '/root/.ssh/known_hosts'
    name: "{{ inventory_hostname }}"
    key: "{{ ssh_known_host_results.stdout }}"
    state: present
  delegate_to: "{{ peertube_ldap_url }}"
  become_user: root

- name: Copy the file certtificate
  become: True
  shell: "rsync -arvz {{ peertube_tls_cert_src }} root@{{ inventory_hostname }}:{{ peertube_tls_cert_dest }}"
  delegate_to: '{{ peertube_ldap_url }}'
