
- include_tasks: install_dependencies.yml

- include_tasks: postgres.yml

- include_tasks: certbot.yml

- include_tasks: nginx.yml

- include_tasks: install_configure_peertube.yml

- include_tasks: copy_ldap_key_tls.yml
  when: not peertube_ldap.insecure_tls
