---

- name: install peertube daemon
  systemd:
    name: peertube
    daemon_reload: yes
    enabled: yes
    state: started

- name: restart peertube daemon
  systemd:
    name: peertube
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded
